"""Phase Gate: generate test_phases.py from frontmatter; evaluate pass/fail."""
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent


@dataclass
class GateResult:
    passed: bool
    reason: str


def generate_test_module(frontmatter: dict, out: Path) -> None:
    """Emit one pytest function per acceptance_tests entry.

    Generated tests start as failing assertions so the gate can detect
    un-implemented tests; the implementer fills each placeholder during
    /pbg-phase work.
    """
    n = frontmatter["phase"]
    body = [
        '"""Auto-generated by /pbg-phase. Edit each test to implement its perturbation/observable."""',
        "import pytest",
        "",
    ]
    for t in frontmatter.get("acceptance_tests", []):
        ident = t["id"].replace(".", "_").replace("-", "_")
        desc = t["desc"].replace('"', '\\"')
        body.append(dedent(f'''\
            def test_{ident}():
                """Phase {n} · {desc}"""
                pytest.fail("not yet implemented — fill in this test during /pbg-phase {n}")
        '''))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(body))


def evaluate_gate(frontmatter: dict) -> GateResult:
    """Decide whether a phase's gate has passed.

    Rules:
    - Empty acceptance_tests list → not passed (no contract).
    - Any test failing → not passed.
    - Any test pending → not passed (work still in flight).
    - All passing → passed.
    """
    statuses = [t.get("status", "pending") for t in frontmatter.get("acceptance_tests", [])]
    if not statuses:
        return GateResult(False, "no acceptance tests defined")
    if any(s == "failing" for s in statuses):
        return GateResult(False, "one or more acceptance tests failing")
    if any(s == "pending" for s in statuses):
        return GateResult(False, "one or more acceptance tests still pending")
    if all(s == "passing" for s in statuses):
        return GateResult(True, "all acceptance tests passing")
    return GateResult(False, f"unexpected statuses: {statuses}")
